"""
Fraud detection Pydantic v2 schemas for SMART EXPENSE AUDITOR.

Covers fraud report public views, AI analysis result payloads, and
aggregate fraud statistics for the dashboard.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field

from app.models.audit_log import FraudReportStatus
from app.models.expense import RiskLevel


# ── Fraud Report ──────────────────────────────────────────────────────────────

class FraudReportPublic(BaseModel):
    """Full public representation of a fraud report generated by the AI pipeline."""

    id: uuid.UUID
    receipt_id: uuid.UUID
    expense_claim_id: uuid.UUID
    organization_id: uuid.UUID

    # AI scores
    fraud_score: float = Field(..., description="Fraud probability [0.0, 1.0]")
    confidence: float = Field(..., description="Model confidence [0.0, 1.0]")

    # Fraud classification
    fraud_types: Optional[list[str]] = Field(
        None,
        description=(
            "List of detected fraud pattern labels, e.g. "
            "['duplicate_receipt', 'inflated_amount', 'fictitious_vendor']"
        ),
    )
    ai_reasoning: Optional[str] = Field(
        None, description="Natural language explanation from the AI model"
    )

    # Review outcome
    is_confirmed: Optional[bool] = Field(
        None,
        description="Null = pending; True = confirmed fraud; False = false positive",
    )
    reviewed_by: Optional[uuid.UUID] = None
    status: FraudReportStatus

    created_at: datetime

    model_config = {"from_attributes": True}


# ── AI Analysis Result ────────────────────────────────────────────────────────

class FraudAnalysisResult(BaseModel):
    """
    Structured output returned by the AI fraud detection service.

    This is the canonical contract between the AI service and the API layer.
    It is stored verbatim in Receipt.ai_analysis and used to create/update
    FraudReport rows.
    """

    fraud_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall fraud probability score",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Model confidence in the fraud_score prediction",
    )
    fraud_types: list[str] = Field(
        default_factory=list,
        description="Detected fraud pattern labels",
        examples=[["duplicate_receipt", "round_number_amount"]],
    )
    ai_reasoning: str = Field(
        ...,
        description="Plain-language explanation of why this was flagged",
    )
    risk_level: RiskLevel = Field(
        ..., description="Derived risk tier based on fraud_score thresholds"
    )
    recommendations: list[str] = Field(
        default_factory=list,
        description="Actionable steps for the finance manager or auditor",
        examples=[
            [
                "Request original physical receipt from the employee.",
                "Cross-check vendor GSTIN against government portal.",
                "Compare with previous claims from the same employee.",
            ]
        ],
    )
    # Optional metadata from specific detection modules
    duplicate_match_id: Optional[uuid.UUID] = Field(
        None, description="ID of the receipt this is suspected to be a duplicate of"
    )
    amount_deviation_pct: Optional[float] = Field(
        None,
        description="Percentage deviation from the statistical norm for this category",
    )
    extra_signals: Optional[dict[str, Any]] = Field(
        None, description="Additional structured signals from detection sub-models"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "fraud_score": 0.87,
                "confidence": 0.91,
                "fraud_types": ["inflated_amount", "suspicious_vendor"],
                "ai_reasoning": (
                    "The claimed amount of ₹48,500 is 312% above the 90th percentile "
                    "for MEALS category in this organization. The vendor GSTIN "
                    "27AABCT1332L1ZL returned an INACTIVE status on the GST portal."
                ),
                "risk_level": "HIGH",
                "recommendations": [
                    "Verify vendor GST registration status on the government portal.",
                    "Request itemized bill from the employee.",
                    "Flag for senior auditor review.",
                ],
                "amount_deviation_pct": 312.5,
            }
        }
    }


# ── Fraud Statistics ──────────────────────────────────────────────────────────

class FraudStats(BaseModel):
    """
    Aggregate fraud statistics for the compliance dashboard.

    Scoped to an organization and optional date range.
    """

    total_detected: int = Field(
        ..., description="Total number of fraud reports generated"
    )
    confirmed_fraud: int = Field(
        ..., description="Reports confirmed as genuine fraud by a reviewer"
    )
    false_positives: int = Field(
        ..., description="Reports dismissed as false positives"
    )
    pending_review: int = Field(
        ..., description="Reports awaiting human review"
    )

    total_amount_at_risk: float = Field(
        ..., description="Cumulative amount (INR) associated with open/investigating reports"
    )
    total_amount_saved: float = Field(
        ..., description="Cumulative amount (INR) recovered by rejecting confirmed fraud"
    )

    fraud_by_type: dict[str, int] = Field(
        default_factory=dict,
        description="Counts of each fraud_type label, e.g. {'duplicate_receipt': 14, ...}",
    )
    fraud_by_category: dict[str, int] = Field(
        default_factory=dict,
        description="Fraud report counts grouped by expense category",
    )

    avg_fraud_score: float = Field(
        ..., description="Mean fraud_score across all reports in scope"
    )
    high_risk_vendors: int = Field(
        ..., description="Distinct vendors with fraud_score > 0.7"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "total_detected": 47,
                "confirmed_fraud": 12,
                "false_positives": 8,
                "pending_review": 27,
                "total_amount_at_risk": 342800.0,
                "total_amount_saved": 89500.0,
                "fraud_by_type": {
                    "duplicate_receipt": 14,
                    "inflated_amount": 19,
                    "fictitious_vendor": 7,
                    "round_number_amount": 7,
                },
                "fraud_by_category": {
                    "TRAVEL": 21,
                    "MEALS": 15,
                    "ACCOMMODATION": 11,
                },
                "avg_fraud_score": 0.73,
                "high_risk_vendors": 5,
            }
        }
    }
